---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: examples
spec:
  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps.git
    - https://github.com/paulbouwer/hello-kubernetes.git
    - https://github.com/niqdev/kotlin-fun.git
  destinations:
    - namespace: examples
      server: https://kubernetes.default.svc
