---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  # ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/argoproj/argo-helm.git
    - {{ .Values.repository.url }}
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
