---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  # ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - {{ .Values.repository.url }}
    - https://github.com/argoproj/argo-helm.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    # fixes "Resource rbac.authorization.k8s.io:ClusterRole is not permitted in project argocd."
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    # fixes "Resource rbac.authorization.k8s.io:ClusterRoleBinding is not permitted in project argocd."
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    # fixes "Resource apiextensions.k8s.io:CustomResourceDefinition is not permitted in project argocd."
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    # fixes "Resource :Namespace is not permitted in project argocd."
    - group: ''
      kind: Namespace
