name: helm-dependencies

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # every 12 hours
    - cron: '0 0,12 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/helm-dependencies.yml'
      - 'dependencies.yaml'

jobs:
  helm-dependencies:
    name: Helm Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Dependencies
        uses: hckops/actions/helm-dependencies-action@v0.9.5
        with:
          config-path: dependencies.yaml
          user-email: "hckbot@users.noreply.github.com"
          user-name: "hckbot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
