name: DigitalOcean cluster

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kube-*.yml'
      - 'clusters/kube-*.yaml'

# TODO notification
jobs:
  kube-do-sample:
    name: Cluster
    runs-on: ubuntu-latest
    steps:
      # TODO add tmp shared path to save kubeconfig (bootstrap)
      - name: Provision
        uses: hckops/actions/kube-do-action@v0.1.0
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: clusters/kube-do-sample.yaml
          enabled: true

      - name: Status
        run: echo "Cluster status ${{ steps.provision.outputs.status }}"
      
      - name: Test
        run: |
          whoami
          pwd
          ls -la
          ls -la ~/
          printenv
