name: kube-do

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kube-do.yml'
      - 'clusters/kube-do-*.yaml'

env:
  BOOTSTRAP_ONLY: true

jobs:
  # cluster provisioning and platform bootstrap
  kube-do-sample:
    name: Provision and Bootstrap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision
        # TODO use tag
        uses: hckops/actions/kube-do-action@main
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: clusters/kube-do-sample.yaml
          enabled: true
          wait: true
          # development only: when true bootstrap without provisioning
          skip: ${{ env.BOOTSTRAP_ONLY }}

      - name: Output
        run: |
          echo "Status: ${{ steps.provision.outputs.status }}"
          echo "KubeConfig: ${{ steps.provision.outputs.kubeconfig }}"
      
      - name: Bootstrap
        if: ${{ steps.provision.outputs.status == 'CREATE' }} || ${{ env.BOOTSTRAP_ONLY }}
        # TODO use tag
        uses: hckops/actions/bootstrap-action@1dd43f3789473b8e7e9852927ea79b52286fb610
        with:
          gitops-ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
          argocd-admin-password: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
          kubeconfig: ${{ steps.provision.outputs.kubeconfig }}
          chart-path: ./argocd-config
          version: HEAD

      - name: Notification
        # TODO use tag
        uses: hckops/actions/discord-action@main
        with:
          action: create-message
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Cluster ${{ github.repository }}: ${{ steps.provision.outputs.status }}"
