name: kube-do

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kube-*.yml'
      - 'clusters/kube-*.yaml'

jobs:
  # EXAMPLE: how to manage simple cluster provisioning
  kube-do-provision-only:
    name: Simple provision
    runs-on: ubuntu-latest
    steps:
      - name: Provision
        uses: hckops/actions/kube-do-action@main
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: clusters/kube-do-sample.yaml
          enabled: false
      - name: Status
        run: echo "Cluster status ${{ steps.provision.outputs.status }}"

  # EXAMPLE: how to provision a cluster and bootstrap a platform
  kube-do-sample:
    name: Provision and bootstrap
    runs-on: ubuntu-latest
    steps:
      # TODO test without checkout IF public
      # required only to bootstrap, not to provision
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision
        # TODO use tag e.g. v0.1.x
        uses: hckops/actions/kube-do-action@main
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: clusters/kube-do-sample.yaml
          enabled: true
          # TODO set to true
          wait: false

      - name: Output
        run: |
          echo "Status: ${{ steps.provision.outputs.status }}"
          echo "Config: ${{ steps.provision.outputs.config }}"

      - name: Notification
        uses: hckops/actions/discord-action@main
        with:
          action: create-message
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Cluster ${{ github.repository }}: ${{ steps.provision.outputs.status }}"

      # TODO run bootstrap only if CREATE
      # TODO see hckops-kube-sample-kubeconfig.yaml in root path
      - name: Test
        # TODO verify IF
        if: ${{ steps.provision.outputs.status == 'CREATE' }}"
        run: |
          whoami
          pwd
          printenv
          ls -la
          ls -la $HOME
