name: kube-do

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kube-do.yml'
      - 'clusters/kube-do-*.yaml'

jobs:
  # cluster provisioning and platform bootstrap
  kube-do-sample:
    name: Provision and Bootstrap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision
        uses: hckops/actions/kube-do-action@v0.4
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: clusters/kube-do-sample.yaml
          enabled: true
          wait: true
          # for development only: if "true" bootstrap without provisioning
          skip: false

      - name: Output
        run: |
          echo "Status: ${{ steps.provision.outputs.status }}"
          echo "KubeConfig: ${{ steps.provision.outputs.kubeconfig }}"
      
      - name: Bootstrap
        if: ${{ steps.provision.outputs.status == 'CREATE' }}
        uses: hckops/actions/bootstrap-action@v0.4
        with:
          gitops-ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
          argocd-admin-password: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
          kubeconfig: ${{ steps.provision.outputs.kubeconfig }}
          chart-path: ./charts/argocd-config
          version: HEAD

      - name: Notification
        # notify also if previous steps failed
        if: ${{ always() }}
        uses: hckops/actions/discord-action@v0.4
        with:
          action: create-message
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Cluster ${{ github.repository }}: ${{ steps.provision.outputs.status }}"
